/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quanlychothuexedulichminhlong;

import com.mycompany.BUL.BULTaiKhoan;
import com.mycompany.DTO.TaiKhoan;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author linus
 */
public class QuanLyTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTaiKhoan
     */
    
    MainForm mainForm = null;
    
    public QuanLyTaiKhoan() {
        initComponents();
        this.setDefaultCloseOperation(SuaDonHang.DISPOSE_ON_CLOSE );
    }
    
    public QuanLyTaiKhoan(MainForm mainForm) {
        initComponents();
        this.mainForm = mainForm;
        this.updateTableTaiKhoan();
        this.setDefaultCloseOperation(SuaDonHang.DISPOSE_ON_CLOSE );
    }
    
    private void updateTableTaiKhoan(){
        String []colsName = {"Tài khoản", "Mật khẩu", "Loại"};
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(colsName);
        BULTaiKhoan bul = new BULTaiKhoan();
        List<TaiKhoan> res = bul.getListTaiKhoan();
        for (int i=0; i<res.size(); i++){
            TaiKhoan tk = res.get(i);
            tableModel.addRow(new Object[]{
                tk.getTenDangNhap(),
                tk.getMatKhau(),
                tk.getLoai(),
            });
        }
        jTable1.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }
    
    private void updateTableTaiKhoanFromSearch(List<TaiKhoan> res){
        String []colsName = {"Tài khoản", "Mật khẩu", "Loại"};
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(colsName);
        for (int i=0; i<res.size(); i++){
            TaiKhoan tk = res.get(i);
            tableModel.addRow(new Object[]{
                tk.getTenDangNhap(),
                tk.getMatKhau(),
                tk.getLoai(),
            });
        }
        jTable1.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        cmbLoai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý tài khoản");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý tài khoản");

        jLabel2.setText("Tài khoản");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Loại");

        txtMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauActionPerformed(evt);
            }
        });

        cmbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master", "Support Customer" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tài khoản", "Mật khẩu", "Loại"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXoa)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnTimKiem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSua))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(277, 277, 277))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean passed = true;
        String tk = txtTaiKhoan.getText();
        if (tk.equals("")){
            passed = false;
            JOptionPane.showMessageDialog(rootPane, "Tài khoản không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String pass = txtMatKhau.getText();
        if (pass.equals("")){
            passed = false;
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String loai = (String) cmbLoai.getSelectedItem();
        if (passed){
            TaiKhoan acc = new TaiKhoan(tk, pass, loai);
            BULTaiKhoan bul = new BULTaiKhoan();
            try {
                bul.themTaiKhoan(acc);
                JOptionPane.showMessageDialog(rootPane, String.format("Thêm thành công!"), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                if (ex.toString().contains("Duplicate entry") && ex.toString().contains(".PRIMARY")){
                    JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, String.format("Đã có lỗi xảy ra! %s", ex), "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
            this.updateTableTaiKhoan();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private int getCmbIndexByLoai(String loai, javax.swing.JComboBox<String> cmb){
        for (int i=0; i<cmb.getItemCount(); i++){
            String selected_item = (String) cmb.getItemAt(i);
            if (selected_item.equals(loai)){
                return i;
            }
        }
        return -1;
    }
    
    private void loadDataFromTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Vector data = (Vector) model.getDataVector().get(jTable1.getSelectedRow());
        txtTaiKhoan.setText((String) data.elementAt(0));
        txtMatKhau.setText((String) data.elementAt(1));
        String loai = (String) data.elementAt(2);
        cmbLoai.setSelectedIndex(getCmbIndexByLoai(loai, cmbLoai));
    }
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        boolean passed = true;
        String tk = txtTaiKhoan.getText();
        if (tk.equals("")){
            passed = false;
            JOptionPane.showMessageDialog(rootPane, "Tài khoản không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String pass = txtMatKhau.getText();
        if (pass.equals("")){
            passed = false;
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không được bỏ trống!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String loai = (String) cmbLoai.getSelectedItem();
        int confimed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa tài khoản không ?","Cảnh báo", JOptionPane.YES_NO_OPTION);
        if (passed && confimed == 0){
            TaiKhoan acc = new TaiKhoan(tk, pass, loai);
            BULTaiKhoan bul = new BULTaiKhoan();
            try {
                bul.suaTaiKhoan(acc);
                JOptionPane.showMessageDialog(rootPane, String.format("Sửa thành công!"), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, String.format("Đã có lỗi xảy ra! %s", ex), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            this.updateTableTaiKhoan();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        loadDataFromTable();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng lựa chọn tài khoản cần xoá trong bảng tài khoản!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int confimed = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá tài khoản không ?","Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (confimed == 0){
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                Vector data = (Vector) model.getDataVector().get(jTable1.getSelectedRow());
                String taiKhoan = (String) data.elementAt(0);
                BULTaiKhoan bul = new BULTaiKhoan();
                try {
                    bul.xoaTaiKhoan(taiKhoan);
                    JOptionPane.showMessageDialog(rootPane, "Xoá thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, String.format("Đã có lỗi xảy ra %s!", ex), "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        updateTableTaiKhoan();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        boolean passed = true;
        String tk = txtTaiKhoan.getText();
        if (tk.equals("")){
            passed = false;
            updateTableTaiKhoan();
        }
        if (passed){
            BULTaiKhoan bul = new BULTaiKhoan();
            List <TaiKhoan> res = bul.timTaiKhoan(tk);
            updateTableTaiKhoanFromSearch(res);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cmbLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
