/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quanlychothuexedulichminhlong;
import com.mycompany.BUL.*;
import com.mycompany.DTO.*;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author linus
 */
public class SuaDonHang extends javax.swing.JFrame {

    /**
     * Creates new form ThemDonHangg
     */
    
    MainForm mainForm = null;
    JTable table = null;
    
    public SuaDonHang(){
        initComponents();
        loadComboBox();
        this.setDefaultCloseOperation(SuaDonHang.DISPOSE_ON_CLOSE );
    }
    
    public SuaDonHang(MainForm mainForm, JTable table) {
        initComponents();
        loadComboBox();
        this.mainForm = mainForm;
        this.table = table;
        loadDataFromTable();
        this.setDefaultCloseOperation(SuaDonHang.DISPOSE_ON_CLOSE );
    }

    private void loadComboBox(){
        // Load khach hang
        BULKhachHang bul_khach = new BULKhachHang();
        List<KhachHang> all_khach = bul_khach.layKhachHang();
        Vector comboBoxItems=new Vector();
        for (int i=0; i<all_khach.size(); i++){
            comboBoxItems.add(String.format("%d-%s", all_khach.get(i).getMaKH(), all_khach.get(i).getHoTen()));
        }
        DefaultComboBoxModel model = new DefaultComboBoxModel(comboBoxItems);
        cmbMaKhachHang.setModel(model);
    
        // Load xe
        BULXe bul_xe = new BULXe();
        List<Xe> all_xe = bul_xe.layXe();
        comboBoxItems=new Vector();
        for (int i=0; i<all_xe.size(); i++){
            comboBoxItems.add(String.format("%s-%s", all_xe.get(i).getLoaiXe(), all_xe.get(i).getBienSo()));
        }
        model = new DefaultComboBoxModel(comboBoxItems);
        cmbBienSo.setModel(model);
    }
    
    private int getCmbIndexByMaKH(int id, javax.swing.JComboBox<String> cmb){
        for (int i=0; i<cmb.getItemCount(); i++){
            String selected_item = (String) cmb.getItemAt(i);
            String[] selected_item_list = selected_item.split("-");
            int extracted_id = Integer.parseInt(selected_item_list[0]);
            if (extracted_id == id){
                return i;
            }
        }
        return -1;
    }
    
    private int getCmbIndexByBienSo(String bienSo, javax.swing.JComboBox<String> cmb){
        for (int i=0; i<cmb.getItemCount(); i++){
            String selected_item = (String) cmb.getItemAt(i);
            String[] selected_item_list = selected_item.split("-");
            if (bienSo.equals(selected_item_list[1])){
                return i;
            }
        }
        return -1;
    }
    
    private void loadDataFromTable(){
        DefaultTableModel model = (DefaultTableModel)this.table.getModel();
        System.out.println(this.table.getSelectedRow());
        Vector data = (Vector) model.getDataVector().get(this.table.getSelectedRow());
        txtMaDon.setText((int) data.elementAt(0) + "");
        cmbMaKhachHang.setSelectedIndex(this.getCmbIndexByMaKH((int) data.elementAt(1), cmbMaKhachHang));
        cmbBienSo.setSelectedIndex(this.getCmbIndexByBienSo((String) data.elementAt(2), cmbBienSo));
        txtDiemDi.setText((String) data.elementAt(3));
        txtDiemDen.setText((String) data.elementAt(4));
        txtNgayDi.setText((String) data.elementAt(5));
        txtNgayVe.setText((String) data.elementAt(6));
        txtGia.setText((long) data.elementAt(7) + "");
        cmbTrangThai.setSelectedItem((String) data.elementAt(8) + "");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtMaDon = new javax.swing.JTextField();
        txtDiemDen = new javax.swing.JTextField();
        txtDiemDi = new javax.swing.JTextField();
        txtNgayDi = new javax.swing.JTextField();
        txtNgayVe = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        cmbMaKhachHang = new javax.swing.JComboBox<>();
        cmbBienSo = new javax.swing.JComboBox<>();
        cmbTrangThai = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sửa đơn hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Mã đơn");

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("Biển số");

        jLabel4.setText("Điểm đến");

        jLabel5.setText("Ngày đi");

        jLabel6.setText("Điểm đi");

        jLabel7.setText("Ngày về");

        jLabel8.setText("Giá");

        jLabel9.setText("Trạng thái");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtMaDon.setEditable(false);
        txtMaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDonActionPerformed(evt);
            }
        });

        txtDiemDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemDenActionPerformed(evt);
            }
        });

        txtDiemDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemDiActionPerformed(evt);
            }
        });

        txtNgayDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayDiActionPerformed(evt);
            }
        });

        txtNgayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayVeActionPerformed(evt);
            }
        });

        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        cmbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang xử lý", "Đã xác nhận", "Đã nhận xe", "Đã thanh toán", "Khác" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiemDen, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtMaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtDiemDi, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtNgayDi, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtNgayVe, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(cmbBienSo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMaKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnSua)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDiemDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
        boolean pass = true;
        int MaDon = 0;
        try{
            MaDon = Integer.parseInt(txtMaDon.getText());
        }
        catch(Exception ex){
            System.out.println(ex);
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Mã đơn không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
        int MaKH = 0;
        try{
            String selected_item = (String)cmbMaKhachHang.getSelectedItem();
            String[] selected_item_list = selected_item.split("-");
            MaKH = Integer.parseInt(selected_item_list[0]);
        }
        catch(Exception ex){
            System.out.println(ex);
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String selected_item = (String)cmbBienSo.getSelectedItem();
        String[] selected_item_list = selected_item.split("-");
        String BienSo = selected_item_list[1];
        String DiemDi = txtDiemDi.getText();
        String DiemDen = txtDiemDen.getText();
        
        DateValidator validator = new DateValidatorUsingDateFormat("yyyy-MM-dd");
        String NgayDi = txtNgayDi.getText();
        if (validator.isValid(NgayDi) == 0){
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Ngày đi không hợp lệ! Vui lòng nhập đúng format yyyy-MM-dd", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String NgayVe = txtNgayVe.getText();
        if (validator.isValid(NgayVe) == 0){
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Ngày về không hợp lệ! Vui lòng nhập đúng format yyyy-MM-dd", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        long Gia = Long.parseLong(txtGia.getText());
        if (Gia < 0){
            pass = false;
            JOptionPane.showMessageDialog(rootPane, "Giá không được âm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        String TrangThai = (String) cmbTrangThai.getSelectedItem();

        if (pass){
            DonHang donhang = new DonHang(MaDon, MaKH, BienSo, DiemDi, DiemDen, NgayDi, NgayVe, Gia, TrangThai);
            BULDonHang bul = new BULDonHang();
            try{
                bul.suaDonHang(donhang);
                JOptionPane.showMessageDialog(rootPane, String.format("Sửa thành công!"), "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
            catch(Exception ex){
                System.out.println(ex);
                JOptionPane.showMessageDialog(rootPane, String.format("Đã có lỗi xảy ra! %s", ex), "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            this.setVisible(false);
            this.mainForm.updateTableDonHang();
            this.dispose();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDonActionPerformed

    private void txtDiemDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemDenActionPerformed

    private void txtDiemDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemDiActionPerformed

    private void txtNgayDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayDiActionPerformed

    private void txtNgayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayVeActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.mainForm.setVisible(true);
        this.mainForm.updateTableDonHang();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cmbBienSo;
    private javax.swing.JComboBox<String> cmbMaKhachHang;
    private javax.swing.JComboBox<String> cmbTrangThai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtDiemDi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaDon;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtNgayVe;
    // End of variables declaration//GEN-END:variables
}
